### ISSUE TITLE
EnergyScheduling experiments not working

### ISSUE THREAD

**Issue by pminervini** [JayMan91/NeurIPSIntopt#2]
Hello, running `PYTHONPATH=. python3 ./exp_run.py` in the `EnergyScheduling` folder leads to this:

```bash
[..]
Epoch[4/11], loss(train):384595.25 @ 2021-01-19 19:36:28 
Epoch[4/12], loss(train):349502.72 @ 2021-01-19 19:37:53 
Epoch[4/13], loss(train):309425.31 @ 2021-01-19 19:39:19 
Epoch[4/14], loss(train):358522.38 @ 2021-01-19 19:40:40 
Epoch[4/15], loss(train):320667.47 @ 2021-01-19 19:41:59 
Epoch[4/16], loss(train):261996.72 @ 2021-01-19 19:43:22 
Epoch[4/17], loss(train):303735.38 @ 2021-01-19 19:44:43 
Epoch[4/18], loss(train):358828.66 @ 2021-01-19 19:46:02 
Epoch[4/19], loss(train):361545.69 @ 2021-01-19 19:47:22 
Epoch[4/20], loss(train):262988.81 @ 2021-01-19 19:48:42 
Epoch[4/21], loss(train):262221.91 @ 2021-01-19 19:50:02 
Epoch[4/22], loss(train):478453.25 @ 2021-01-19 19:51:23 
Epoch[4/23], loss(train):354604.09 @ 2021-01-19 19:52:45 
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Epoch[1/1] fwd pass not solved
Traceback (most recent call last):
  File "./exp_run.py", line 71, in <module>
    clf.fit(X_1gtrain,y_train,X_test= X_1gtest,y_test= y_test)
  File "../../Interior/intopt_energy_mlp.py", line 627, in fit
    i+1, loss.item(),datetime.datetime.now() ))
UnboundLocalError: local variable 'loss' referenced before assignment
```

It's pretty easy to fix, I can do a pull request later today.

**Comment by JayMan91** [comment]
Thank you for pointing it out. My latest commit hopefully solve this issue. If not feel free to fix.
